[shell]
program = "/usr/bin/zsh"

[font]
size = 10

[font.normal]
family = "SpaceMono Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.7 

[window.padding]
x = 10
y = 10
